apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: final
  name: namespace-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: final
  name: namespace-role-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: namespace-role
  apiGroup: rbac.authorization.k8s.io