apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: final
spec:
  selector:
    app: flask-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
