apiVersion: v1
kind: Service
metadata:
  name: my-db
  namespace: final
spec:
  selector:
    app: my-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306